### ISSUE TITLE
Renamed packages show up as new

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/addons.silverstripe.org#162]
Although technically correct, the namechange of Symbiote has shown that the "new" section shouldn't be populated with namechanges, as they take over the actual "new" modules.

**Comment by robbieaverill** [comment]
Yeah - this would be resolved by [marking abandoned packages as abandoned rather than deleting them](https://github.com/silverstripe/addons.silverstripe.org/issues/159), which is a flow on issue from a previous pull request that deletes abandoned packages entirely.

For reference, that change hasn't been deployed to production yet, which is why you're seeing both the abandoned package and the new one show up in the same way.

Ideally (following #159 and deployment) the SSAU packages will show as abandoned like they do in Packagist and give the user a link to the replacement.
